### ISSUE TITLE
Problem with 419 | Page Expired.

### ISSUE THREAD

**Issue by Burans** [takepart-media/statamic-oreos#10]
Hey! I'm having trouble getting Oreos to work.
Whatever I do when I submit the form I get `419 | Page Expired` .
Tried clearing all the caches, uninstalling and reinstalling oreos but no luck. Static caching is off.
Any ideas what could be the problem? Thank you!

**Comment by terryosayawe** [comment]
This is related to cache follow the steps below to resolve it 

For anyone facing this issue I resolved it by excluding all things related to cookie consent from cache using `nocache` tag like so

```
     ...
    {{ nocache }}
        {{ oreos:popup }}
    {{ /nocache }}
</body>
```

Publish assets and update like so: 
In `resources/views/vendor/statamic-oreos/form.antlers.html` wrap the entire content with `nocache` tag 
```
{{ nocache }}
<form action="{{ route:statamic.oreos.save }}" method="post">
    <input type="hidden" name="_token" value="{{ csrf_token }}">

 ...
</form>
{{ /nocache }}
```

Finally in `resources/views/vendor/statamic-oreos/popup.antlers.html` do the same 
```
{{ nocache }}
<div id="oreos-popup" class="fixed bottom-4 right-4 p-4 max-w-2xl shadow-md bg-white z-10">
    <h2 class="font-semibold text-4xl mb-4">
        Title
    </h2>
    
    <p>Text </p>

    {{ oreos:form }}
</div>
{{ /nocache }}
```

**Comment by markverg** [comment]
thanks!
