### ISSUE TITLE
Oreos Cookie Manager and caching

### ISSUE THREAD

**Issue by marflow** [takepart-media/statamic-oreos#5]
Hello takepart-media,

thanks for providing the addon. I would like to use it together with Statamic caching strategy 'half`, but it seems that is not possible? If the site is loaded with caching enabled the banner will not disappear, if enabled after giving consent, the site will be unreachable when the Oreos cookie has expired. Am I doing something wrong?

Thanks for your thoughts,
Wolfram

**Comment by jaygeorge** [comment]
I'm not 100% sure if this is the same issue but every now and again (not always) when I click 'save' to accept on the cookie consent I get redirected to https://mysite.com/!/statamic-oreos/save followed by a 419 page expired error.

I've tried turning off half measure caching, for now, to see if this fixes things, but at the same time, I'd _really_ like to use half measure caching so I hope this is something that can be fixed.

**Comment by ghost** [comment]
Hey both of you,

unfortunately the addon does not work well with enabled caching right now, as all the checks to show or hide the banner are done server-side. We have certain plans to improve that in future, but no ETA right now, sorry.

@JayGeorge this seems to be related, yes, though I don't have the time to investigate it further – will do so once we'll provide the next update.

Thanks and have a nice day!

**Comment by terryosayawe** [comment]
For anyone facing this issue I resolved it by excluding all things related to cookie consent from cache using `nocache` tag like so

```
     ...
    {{ nocache }}
        {{ oreos:popup }}
    {{ /nocache }}
</body>
```

Publish assets and update like so: 
In `resources/views/vendor/statamic-oreos/form.antlers.html` wrap the entire content with `nocache` tag 
```
{{ nocache }}
<form action="{{ route:statamic.oreos.save }}" method="post">
    <input type="hidden" name="_token" value="{{ csrf_token }}">

 ...
</form>
{{ /nocache }}
```

Finally in `resources/views/vendor/statamic-oreos/popup.antlers.html` do the same 
```
{{ nocache }}
<div id="oreos-popup" class="fixed bottom-4 right-4 p-4 max-w-2xl shadow-md bg-white z-10">
    <h2 class="font-semibold text-4xl mb-4">
        Title
    </h2>
    
    <p>Text </p>

    {{ oreos:form }}
</div>
{{ /nocache }}
```
I hope this helps!
