### ISSUE TITLE
Support Statamic 3.3

### ISSUE THREAD

**Issue by pushpanda** [takepart-media/statamic-oreos#6]
Can you please check support for 3.3 for Oreos. Would this be as straightforward as updating the version constraints in the composer.json file?

**Comment by Pantastisch** [comment]
@jackmcdade made a PR (https://github.com/takepart-media/statamic-oreos/pull/7) for that.

You can use his implementation by adapting your `composer.json`, till this is merged here.

```
    "require": {
        "takepart-media/statamic-oreos": "dev-main",
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/jackmcdade/statamic-oreos"
        }
    ]
```
